README.md

Launch should be made via bash

sh is not good to launch the setup script.

---

images/changelog/Dockerfile

feat: added image allowing to generate a changelog for a given version

---

environments/ci/docker-compose.yml

feat(ci): create a ci environment with jenkins, sonar and redis

---

environments/demo/common.yml
environments/demo/docker-compose-local.yml
environments/demo/docker-compose-traefik-latest.yml
environments/demo/docker-compose-traefik-nightly.yml

chore(yml): Remove usage of env variables from gravitee.yml

---

environments/demo/common.yml

fix elasticseach going down because mem problems as explained in #1274

fix(compose): fix elasticseach going down because mem problems as explained in #1274

---

images/java/Dockerfile

I changed the base image to openjdk, build all containers and fired up docker-compose-local.
Everything looks good for me.

change java base image to use openjdk

---

images/management-ui/Dockerfile
images/management-ui/Dockerfile-nightly

closes gravitee-io/issues#2277

chore(): update alpine image version

---

environments/components/docker-compose.yml

chore: Dockerize UI projects

---

images/gateway/Dockerfile
images/management-api/Dockerfile

Closes gravitee-io/issues#3372

chore: Use multi-stage to build APIM GW and Mgmt-API

---

README.adoc
apim/1.x/docker-compose.yml

Closes gravitee-io/issues#3351

chore: new docker-compose for APIM 1.x

---

images/portal-ui/Dockerfile
images/portal-ui/Dockerfile-nightly

chore: Generate dist on the root

---

apim/3.x/docker-compose.yml
platform/3.x/docker-compose.yml

Closes gravitee-io/issues#4094

docker: Use non-root ports to run nginx

---

environments/demo/docker-compose-traefik-nightly.yml

This reverts commit b6e96d90e06ff4c2edb14dfcd50bcc824aa2afa6.

Revert "feat(nightly): map mongodb container port to docker host"

---

cicd-lib/circleci/orbs/python/package_bundles.py

https://github.com/gravitee-io/issues/issues/1581

feat: add new tracer plugin

---

enterprise/apim/3.x/management-api/Dockerfile
images/management-api/Dockerfile
images/management-api/Dockerfile-nightly

feat: change zip & folder name in docker file

---

enterprise/am/3.x/gateway/Dockerfile
enterprise/am/3.x/management-api/Dockerfile
enterprise/apim/3.x/gateway/Dockerfile
enterprise/apim/3.x/management-api/Dockerfile
images/gateway/Dockerfile-nightly
images/management-api/Dockerfile-nightly
images/management-ui/Dockerfile
images/management-ui/Dockerfile-nightly
images/portal-ui/Dockerfile-nightly

* Upgrade Nginx base image and upgrade libgcrypt for UIs
* Upgrade OpenJDK Base Image for Management API & Gateway
gravitee-io/issues#6139

chore: Upgrade some base images

---

images/management-ui/Dockerfile-nightly

feat: add management webui in monorepo

---

enterprise/am/3.x/gateway/Dockerfile
enterprise/am/3.x/management-api/Dockerfile
enterprise/apim/3.x/gateway/Dockerfile
enterprise/apim/3.x/management-api/Dockerfile
images/changelog/Dockerfile
images/dynamodb/Dockerfile
images/fpm/rpm/Dockerfile
images/gateway/Dockerfile
images/gateway/Dockerfile-nightly
images/httpd/Dockerfile
images/java/Dockerfile
images/jenkins/Dockerfile
images/management-api/Dockerfile
images/management-api/Dockerfile-nightly
images/management-ui/Dockerfile
images/management-ui/Dockerfile-nightly
images/portal-ui/Dockerfile-nightly
images/python/Dockerfile

I have updated the Dockerfile images to point at the lastest versions we are supporting for now, also updated some dependancies and config.

Change FROM image in Dockerfiles

---

enterprise/am/3.x/gateway/Dockerfile
enterprise/am/3.x/management-api/Dockerfile

* Update the EE base image from adoptOpenJDK to eclipse temurin for API & GW images

chore: update AM EE base images from adoptopenjdk to eclipse-temurin

---

images/package_bundle_py/package_bundles.py

**Issue** 
https://github.com/gravitee-io/issues/issues/6140
Update script used during package bundling to handle the migration of APIM Gateway inside APIM Monorepo

Update script to handle APIM Gateway inside APIM Monorepo

---

.circleci/config.yml

chore: adapt docker images generation

---

.circleci/config.yml
images/java/Dockerfile

Created Java 17 image based on Alpine from Eclipse Temurin.
**Additional Info**
1. Created CircleCI pipeline to automatically release and rebuild the image on a schedule.

feat: java 17 alpine

---

enterprise/am/3.x/gateway/Dockerfile
enterprise/am/3.x/management-api/Dockerfile

closes: https://github.com/gravitee-io/issues/issues/6853

chore: upgrade AM Dockerfile to openjdk-17

---

.circleci/config.yml

The version should be `1.21` not `1.12` 🙈

fix: nginx tag version

---

.circleci/config.yml

**Issue**
https://github.com/gravitee-io/issues/issues/7380
Migrate from secrethub to keep

chore: migrate from secrethub to keeper for AM docker images build

---

images/package_bundle_py/package_bundles.py

**Issue**
https://github.com/gravitee-io/issues/issues/7620
* repository has been merged into APIM repository
* reporter is in its own GH repository

split gravitee-elasticsearch

---

.circleci/config.yml
images/java/Dockerfile

This PR is trying to add support for both amd64 and arm64 platforms
https://gravitee.slab.com/posts/apim-multi-platform-support-0uaxzrgc

feat: add support for arm64 architecture

---

.circleci/config.yml
images/java/Dockerfile
images/nginx/Dockerfile

This PR is adding support for multi-platform support for the front-end nginx image
https://gravitee.slab.com/posts/apim-multi-platform-support-0uaxzrgc

feat: add support for both arm64 and amd64 platforms

---

images/nginx/Dockerfile

This PR is trying to upgrade confd version of our nginx image to its latest version.

fix: upgrade confd

---

.circleci/config.yml

Fetch Docker credential from KSM
**Additional context**

chore(CI): fetch DOCKER credential from KSM

---

.circleci/config.yml
images/nginx/Dockerfile

Upgrade nginx to 1.24 for our custom image

feat(nginx): upgrade to 1.24

---

.circleci/config.yml

**Issue**
Snyk makes a local copy of the imported Docker image. If we don't re-import the project, the new image is never scanned.
This PR forces re-import every time we build an image.

feat(snyk): add snyk import for nginx

---

images/java/Dockerfile

**Issue**
https://gravitee.atlassian.net/browse/DEVOPS-296
Update docker java image to 17.0.9

feat: update docker java image to 17.0.9_9

---

apim/4.x/docker-compose.yml

**Issue**
N/A
Add default configuration for the portal URL.

fix: add default configuration for the portal URL

---

.circleci/config.yml

**Issue**
N/A
Distinct java images generation and add alpine:3.20 to snyk.

ci: distinct java image generation

---

.circleci/config.yml

**Issue**
https://gravitee.atlassian.net/browse/APIM-7000
Build a java 17 image base on alpine 3.18 to fix an issue with DNS resolution

chore: build a java 17 image based on alpine 3.18

---

.circleci/config.yml

**Issue**
https://github.com/gravitee-io/issues/issues/TT-5676

feat(nginx): update base image from 1.27.1 to 1.27.2

---

.circleci/config.yml

**Issue**
https://github.com/gravitee-io/issues/issues/TT-5681
As we migrate from Snyk to Aqua, this update the CI to scan all our images with aqua.

ci: replace Snyk scan by Aqua

---

.circleci/config.yml
images/java/Dockerfile

**Issue**
https://gravitee.atlassian.net/browse/CJ-3089
- fix(java-17): upgrade to jre/jdk 17.0.15
- chore(java-17): upgrade alpine base image to 3.20
- ci(java-17): remove alpine 17/18 builds
- ci(java-17): build & publish 17-alpine-3.21
**Additional context**

fix(java-17): upgrade to jre/jdk 17.0.15

---

.circleci/config.yml

**Issue**
N/A
Quick fix for discussed issue
**Additional context**

Assistance - Update config.yml 
